name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'README.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}

      - name: Build documentation
        run: |
          cargo doc --no-deps --all-features --document-private-items
          
          # Create index.html that redirects to the crate docs
          echo '<!DOCTYPE html>
          <html>
          <head>
              <meta http-equiv="refresh" content="0; url=quot/index.html">
              <title>quot Documentation</title>
          </head>
          <body>
              <p>Redirecting to <a href="quot/index.html">quot documentation</a>...</p>
          </body>
          </html>' > target/doc/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

  deploy-docs:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
